using LinkGuardiao.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LinkGuardiao.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112174500_FixPostgresSchema")]
    public partial class FixPostgresSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            migrationBuilder.Sql(
                "ALTER TABLE \"Users\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
            migrationBuilder.Sql(
                "ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
            migrationBuilder.Sql(
                "ALTER TABLE \"LinkAccesses\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql(
                "ALTER TABLE \"Users\" ALTER COLUMN \"CreatedAt\" TYPE timestamp with time zone USING (\"CreatedAt\"::timestamptz);");
            migrationBuilder.Sql(
                "ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"CreatedAt\" TYPE timestamp with time zone USING (\"CreatedAt\"::timestamptz);");
            migrationBuilder.Sql(
                "ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"ExpiresAt\" TYPE timestamp with time zone USING (NULLIF(\"ExpiresAt\", '')::timestamptz);");
            migrationBuilder.Sql(
                "ALTER TABLE \"LinkAccesses\" ALTER COLUMN \"AccessTime\" TYPE timestamp with time zone USING (\"AccessTime\"::timestamptz);");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"LinkAccesses\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");

            migrationBuilder.Sql(
                "ALTER TABLE \"Users\" ALTER COLUMN \"CreatedAt\" TYPE text USING (\"CreatedAt\"::text);");
            migrationBuilder.Sql(
                "ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"CreatedAt\" TYPE text USING (\"CreatedAt\"::text);");
            migrationBuilder.Sql(
                "ALTER TABLE \"ShortenedLinks\" ALTER COLUMN \"ExpiresAt\" TYPE text USING (\"ExpiresAt\"::text);");
            migrationBuilder.Sql(
                "ALTER TABLE \"LinkAccesses\" ALTER COLUMN \"AccessTime\" TYPE text USING (\"AccessTime\"::text);");
        }
    }
}
